### ISSUE TITLE
Úkol č.2

### ISSUE THREAD

**Issue by HelenaSmerdova** [HelenaSmerdova/Phyton#2]
https://github.com/HelenaSmerdova/Phyton/blob/master/python/ukol_02_01.py

posílám druhý úkol - vypsání států ze seznamu, zatím bez bonusu, nad tím stále přemýšlím ;-)

**Comment by HelenaSmerdova** [comment]
Tady je konečná verze, i s bonusem :-)
https://github.com/HelenaSmerdova/Phyton/blob/master/python/ukol_02_02.py
Doufám, že už ok (v té první verzi jsem si ještě našla chybu).

**Comment by MonikaDvorackova** [comment]
Máš to krásné, vše funguje, žádný problém. Bonus je parádní! :) Díky moc.
