### ISSUE TITLE
Úkol č.9 - Adopce zvířat

### ISSUE THREAD

**Issue by HelenaSmerdova** [HelenaSmerdova/Phyton#9]
https://github.com/HelenaSmerdova/Phyton/commit/058becc26a158be74a925591aef1fa040d6a2066
odevzdávám úkol č.9 - Adopce zvířat.

**Comment by MonikaDvorackova** [comment]
Ahoj Heli, všechno úplně v pořádku, děkuju i za bonus, nemám co vytknout nebo upravit. Jsi hrozně šikovná! :)
